export const cartridges = [
  {
    id: '1',
    brand: 'Canon',
    model: '737',
    alternativeCartridges: ['737 starter L', 'HP CRG737/CF283X', 'HP 83A'],
    compatiblePrinters: [
      'Canon mf212w',
      'Canon mf232w',
      'Canon mf237w',
      'Canon mf244w',
    ],
    barcode: '1234567890123',
    status: 'заправлений',
    location: '',
    responsible: 'Mykola',
    notes: '',
  },
  {
    id: '2',
    brand: 'Canon',
    model: '051',
    alternativeCartridges: ['HP 30A'],
    compatiblePrinters: ['Canon mf264dw', 'Canon mf267dw'],
    barcode: '1234567890124',
    status: 'заправлений',
    location: '',
    responsible: 'Mykola',
    notes: '',
  },
  {
    id: '3',
    brand: 'Canon',
    model: '057',
    alternativeCartridges: [],
    compatiblePrinters: ['Canon mf453dw', 'Canon mf455dw'],
    barcode: '1234567890125',
    status: 'на заправці',
    location: '',
    responsible: 'Mykola',
    notes: '',
  },
  {
    id: '4',
    brand: 'Canon',
    model: '057',
    alternativeCartridges: [],
    compatiblePrinters: ['Canon mf453dw', 'Canon mf455dw'],
    barcode: '1234567890126',
    status: 'в принтері',
    location: '',
    responsible: 'Mykola',
    notes: '',
  },
  {
    id: '5',
    brand: 'Canon',
    model: '071',
    alternativeCartridges: [],
    compatiblePrinters: ['Canon mf275w'],
    barcode: '1234567890127',
    status: 'закінчився',
    location: '',
    responsible: 'Mykola',
    notes: '',
  },
  {
    id: '6',
    brand: 'Canon',
    model: '071',
    alternativeCartridges: [],
    compatiblePrinters: ['Canon mf275w'],
    barcode: '1234567890128',
    status: 'в принтері',
    location: '',
    responsible: 'Mykola',
    notes: '',
  },
];
