export const TEXT = {
  titles: {
    addCartridge: 'Додати новий картридж',
    editCartridge: 'Редагувати картридж',
    addLocation: 'Додати нове розташування',
    editLocation: 'Редагувати розташування',
  },
  fields: {
    totalCartridges: 'Всього картриджів',
    actionsTitle: 'Дії',
    sku: 'ШК',
    compatiblePrinters: 'Сумісні принтери',
    alternativeCartridges: 'Альтернативні картриджі',
    responsible: 'Відповідальний',
    location: 'Розташування',
    refilledDate: 'Отримали після заправки',
    inPrinterDate: 'Встановлено в принтер',
    onRefillDate: 'Передали на заправку',
    endDate: 'Закінчився тонер',
    numberPrintedPagesOfPrinter: 'К-сть роздрук. стор. принтера',
    quantityPages: 'К-сть роздрук. сторінок',
    barcode: 'Штрихкод',
    brand: 'Бренд',
    model: 'Модель',
    status: 'Статус',
    notes: 'Примітка',
    name: 'Назва',
  },
  buttons: {
    add: 'Додати',
    edit: 'Редагувати',
    delete: 'Видалити',
    showBarcode: 'Показати штрихкод',
    changeStatus: 'Змінити статус',
    addCartridge: 'Додати картридж',
    saveChanges: 'Зберегти зміни',
  },
  placeholders: {
    enterBarcode: 'Введіть штрихкод EAN13',
    enterAlternativeCartridges: 'Введіть картриджі через кому',
    enterCompatiblePrinters: 'Введіть принтери через кому',
  },
  validation: {
    required: "Це поле є обов'язковим",
    minLengthBarcode: 'ШК має містити  не менше 13 цифр',
    maxLengthBarcode: 'ШК має містити не більше 13 цифр',
    invalidBarcode: 'Штрихкод має містити лише цифри',
    minLengthBrand: 'Бренд має містити щонайменше 2 символи',
    minLengthModel: 'Модель має містити щонайменше 2 символи',
    minLengthCompatiblePrinters:
      'Сумісні принтери мають містити щонайменше 1 символ',
    minLengthLocation: 'Розташування має містити щонайменше 2 символи',
    minLengthName: 'Назва має містити щонайменше 2 символи',
    minLengthResponsible: 'Відповідальний має містити щонайменше 2 символи',
  },
  dialog: {
    deleteTitle: 'Видалення',
    message: 'Ви впевнені, що хочете видалити?',
    yesBtn: 'Так',
    noBtn: 'Ні',
  },
} as const;
