export const TEXT = {
  titles: {
    addCartridge: 'Додати новий картридж',
    editCartridge: 'Редагувати картридж',
  },
  fields: {
    totalCartridges: 'Всього картриджів',
    actionsTitle: 'Дії',
    sku: 'ШК',
    compatiblePrinters: 'Сумісні принтери',
    alternativeCartridges: 'Альтернативні картриджі',
    responsible: 'Відповідальний',
    location: 'Розташування',
    lastRefillDate: 'Дата ост. заправлення',
    nextRefillDate: 'Дата наст. заправлення',
    barcode: 'Штрихкод',
    brand: 'Бренд',
    model: 'Модель',
    status: 'Статус',
    notes: 'Примітки',
  },
  buttons: {
    add: 'Додати',
    edit: 'Редагувати',
    delete: 'Видалити',
    showBarcode: 'Показати штрихкод',
    changeStatus: 'Змінити статус',
    addCartridge: 'Додати картридж',
    saveChanges: 'Зберегти зміни',
  },
  placeholders: {
    enterBarcode: 'Введіть штрихкод EAN13',
    enterAlternativeCartridges: 'Введіть картриджі через кому',
    enterCompatiblePrinters: 'Введіть принтери через кому',
  },
  validation: {
    required: "Це поле є обов'язковим",
    minLengthBarcode: 'ШК має містити  не менше 13 цифр',
    maxLengthBarcode: 'ШК має містити не більше 13 цифр',
    invalidBarcode: 'Штрихкод має містить лише цифри',
    minLengthBrand: 'Бренд має містити щонайменше 2 символи',
    minLengthModel: 'Модель має містити щонайменше 2 символи',
    minLengthCompatiblePrinters:
      'Сумісні принтери мають містить щонайменше 1 символ',
    minLengthLocation: 'Розташування має містить щонайменше 2 символи',
    minLengthResponsible: 'Відповідальний має містити щонайменше 2 символи',
  },
} as const;
