name: Deploy frontend-cartridges

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 20m
          script: |
            set -e

            cd /home/deployer/apps/frontend-cartridges

            git fetch origin main
            git reset --hard origin/main

            npm ci --legacy-peer-deps
            npm run build

            # Копіюємо білд у директорію Nginx
            sudo rm -rf /var/www/cartridge/browser
            sudo cp -r dist/ng-cartridges/browser /var/www/cartridge/browser
            sudo chown -R www-data:www-data /var/www/cartridge/browser

            # Перевіряємо конфіг і перезавантажуємо Nginx
            sudo nginx -t && sudo systemctl reload nginx

            pm2 delete frontend-cartridges || true
            pm2 serve /home/deployer/apps/frontend-cartridges/dist/ng-cartridges/browser 4201 --name frontend-cartridges --spa
            pm2 save
